# Generated by Django 4.0.5 on 2022-12-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_statusmyapp_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('comment_dt', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Комменарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
